apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-post-install-script
  namespace: {{ .Release.Namespace }}
data:
  keycloak_config.sh: |-
{{- tpl ($.Files.Get "aux/keycloak_config.sh") . | nindent 4 }}
