{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: {{ if not .Values.ingress.namespace }}{{ .Release.Namespace }}{{ else }}{{ .Values.ingress.namespace }}{{ end }}
spec:
  {{- if ne .Values.ingress.className "" }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- if .Values.https.enabled -}} 
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
