apiVersion: v1
kind: Secret
metadata:
  name: keycloak-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.admin.username }}
  KEYCLOAK_ADMIN_PASSWORD: {{ if ne .Values.admin.password "" }}{{ .Values.admin.password | quote }}{{ else }}{{ randAlphaNum 12 | quote }}{{ end }}
  INIT_USER_PASSWORD: {{ if ne .Values.initUser.password "" }}{{ .Values.initUser.password | quote }}{{ else }}{{ randAlphaNum 12 | quote }}{{ end }}
