{{- if .Values.openshift.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  host: {{ .Values.openshift.host }}
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
