# replace "aks-cicd-16661.cicd.cnvrg.me" with the OCP base domain
# kubectl create namespace keycloak
# oc -n keycloak adm policy add-scc-to-user anyuid -z keycloak-sa
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: test
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /opt/keycloak/data']
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      containers:
      - command:
        - /opt/keycloak/bin/kc.sh
        - start-dev
        env:
        - name: KEYCLOAK_ADMIN
          value: itayadmin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "123456"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "true"
        - name: KC_HOSTNAME
          value: keycloak.aks-cicd-16661.cicd.cnvrg.me
        - name: KC_HOSTNAME_ADMIN_URL
          value: https://keycloak.aks-cicd-16661.cicd.cnvrg.me
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:latest
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
      serviceAccountName: keycloak-sa
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
