kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: keycloak-role
rules:
- apiGroups: ["*"]
  resources: ["secrets","pods"]
  verbs: ["create","list"]
